name: build

on:
  workflow_dispatch:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    strategy:
      matrix:
        include: [
            { name: windows_x86, arch: x86 },
            { name: windows_x64, arch: x64 },
        ]

    name: ${{ matrix.name }}

    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: setup VC-LTL
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget install VC-LTL

    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: configure
      run: xmake f -a ${{ matrix.arch }}

    - name: build
      run: xmake

    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.name }}
        path: build/release
        
    - name: compress the build files for release publish
      working-directory: build/release/
      run: |
        7z a -r chrome_plus_${{ matrix.name }}_${{ github.ref_name }}.zip *

    - name: upload to releases
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: build/release/chrome_plus_*.zip
        tags: true
        draft: false
        overwrite: true

